import { useEffect, useRef } from 'react';
import { companyGroups, companyReports, companyEvents, eventTimeline, milestoneReport, isVisible } from './catalog.js';
import { eventTypeLabels, evidenceLevelLabels, reviewResultLabels } from './domain/catalog.js';
import { OutLink, ReportRow } from './components.jsx';
import { DateControls } from './update-components.jsx';

function Review({ review }) {
  if (!review) return <p className="muted">本轮未作专项检查；不能据此判断没有新增事项。</p>;
  return <details className="review-detail"><summary>核查范围 · {reviewResultLabels[review.result]} · 尝试日 {review.lastAttemptAt || '未记录'}</summary><p>{review.note}</p>{review.checks.map(check => <div className="review-channel" key={check.id}><OutLink href={check.url} className="text-link">{check.channel}</OutLink><p>{reviewResultLabels[check.result]} · 尝试 {check.attemptedAt} · {check.checkedThrough ? `已完成区间 ${check.checkedFrom} 至 ${check.checkedThrough}` : '未声明完整覆盖区间'}</p><p>{check.note}</p></div>)}</details>;
}

export function CompanyBrowser({ data, sources, filters, onCompany }) {
  const groups = companyGroups(data);
  const scopedEvents = company => !filters.companies?.length || filters.companies.includes(company.id) ? companyEvents(data,company.id,filters) : [];
  const allEvents = new Set(groups.flatMap(group => group.items.flatMap(company => scopedEvents(company).map(event => event.id))));
  const groupContent = group => <div className="company-group">{group.items.map(company => {
    const docs=!filters.companies?.length || filters.companies.includes(company.id) ? companyReports(data,sources,company.id,filters) : [],events=scopedEvents(company);
    return <article className="company-row" key={company.id} data-company-id={company.id}><div><h3><button className="source-title" onClick={e=>onCompany(company.id,e)}>{company.name}</button></h3><p>{company.securities.map(s=>`${s.exchange}:${s.code}`).join(' / ') || company.legalName}</p><p className="muted">当前范围 {docs.length} 条资料 · {events.length} 项事项</p>{events[0] ? <p className="company-latest">{events[0].currentSummary}</p> : <p className="muted">{docs.length ? '本轮未收录需持续跟踪的重要事项，不代表没有公司动作。' : '当前范围暂无已收录资料；公司入口保留，可调整地区或资料筛选。'}</p>}</div><button className="button secondary" onClick={e=>onCompany(company.id,e)} aria-label={`查看${company.name}公司全景`}>公司全景</button></article>;
  })}</div>;
  return <section aria-label="按公司浏览"><div className="results-heading" id="results" tabIndex={-1}><h2>按公司浏览</h2><span className="muted">6 家核心 · 3 家运营商 · 7 家参考</span></div><details className="data-explanation"><summary>公司资料与计数说明</summary><p>公司全景汇总各研究方向的明确关联资料。当前范围共 {allEvents.size} 项不同事项，同一事项跨公司只计一次；下列公司行中的事项数不相加。</p></details>{groups.map(group=>group.id==='reference'?<details className="company-reference" key={group.id}><summary>{group.name}（{group.items.length}）</summary>{groupContent(group)}</details>:<section key={group.id}><h3 className="region-group-title">{group.name}</h3>{groupContent(group)}</section>)}</section>;
}

export function EventCard({ event, data, expanded, onEvent }) {
  const latest=event.milestones.find(node=>node.id===event.latestVerifiedMilestoneId),evidence=milestoneReport(latest,data);
  return <article className="event-card" data-event-id={event.id}><div className="report-topline"><span>{eventTypeLabels[event.type]} · {event.regions.join(' / ') || '地区待核'}</span></div><h3><button className="source-title" onClick={()=>onEvent(event.id)}>{event.title}</button></h3><p className="event-current" data-current-summary={event.id}>{event.currentSummary}</p><p className="event-date">最新已核节点原披露日：{evidence?.publishedAt || '暂无已核节点'}{evidence && <> · <OutLink href={evidence.url} className="text-link">依据原文</OutLink></>}</p>{event.uncertainties.length>0 && <p className="event-caution">{event.uncertainties[0]}</p>}<details open={expanded || undefined} className="event-evidence"><summary>进展与依据（{event.milestones.length}）</summary><ul className="event-limits">{event.uncertainties.map(note=><li key={note}>{note}</li>)}</ul><p>参与方：{event.participants.map(p=>`${data.companies.find(c=>c.id===p.companyId)?.name || p.name}（${p.role}）`).join('；')}</p><ol className="event-timeline">{eventTimeline(event,data).map(node=>{const primary=milestoneReport(node,data);return <li key={node.id}><h4>{node.title}</h4><p>{evidenceLevelLabels[node.verificationLevel]} · {node.isProgress ? '事项进展节点' : '线索 / 背景，非已核进展'}</p><p>原披露日 {primary?.publishedAt || '待核'} · 事项发生日 {node.occurredAt || '未单列 / 待核'} · 成功核查 {primary?.verifiedAt || '无成功记录'}</p><p>{node.summary}</p>{node.evidenceRefs.map(ref=>{const report=data.reports.find(r=>r.id===ref.reportId);return <p key={`${ref.reportId}-${ref.locator}`}><OutLink href={report.url} className="text-link">{report.title}</OutLink><span> · {ref.role} · {ref.locator}</span></p>;})}</li>;})}</ol><Review review={event.review} />{event.relatedEventIds.map(id=><p key={id}>相关但独立的事项：<button className="text-link" onClick={()=>onEvent(id)}>{data.events.find(e=>e.id===id)?.title}</button></p>)}</details>{!expanded && <button className="text-link event-open" onClick={()=>onEvent(event.id)}>打开事项独立链接</button>}</article>;
}

export function CompanyPanorama({ data, sources, companyId, eventId, eventType, filters, onDateChange, onBack, onEvent, onEventType, onSource }) {
  const titleRef=useRef(null);
  useEffect(()=>{titleRef.current?.focus();},[companyId,eventId]);
  const company=data.companies.find(c=>c.id===companyId), selected=data.events?.find(e=>e.id===eventId);
  if(!company || (eventId && (!selected || !selected.companyIds.includes(companyId) || !isVisible(selected,filters)))) return <section className="empty-state"><h2 ref={titleRef} tabIndex={-1}>公司或事项链接已失效</h2><p>没有替换为其他公司。原筛选条件保留。</p><button className="button secondary" onClick={onBack}>返回原检索</button></section>;
  const events=companyEvents(data,companyId,{...filters,eventType}), docs=companyReports(data,sources,companyId,filters);
  const official=sources.filter(s=>s.sourceType==='company'&&s.companyIds?.includes(companyId)&&isVisible(s,filters));
  return <section className="company-panorama" id="results" tabIndex={-1}><div className="company-heading"><div><h2 ref={titleRef} tabIndex={-1}>{company.name} · 公司全景</h2><p>{company.legalName} · {company.securities.map(s=>`${s.exchange}:${s.code}`).join(' / ')}</p></div><button className="button secondary" onClick={onBack}>返回原检索</button></div><details className="data-explanation"><summary>公司浏览说明</summary><p>跨研究方向汇总明确关联资料，保留原主类。地区同时影响事项和资料；关键词、类型、获取条件、频率和日期只用于资料列表，不改变事项当前结论。切换研究方向返回普通检索。</p></details><Review review={company.disclosureReview} /><div className="event-heading"><h3>重要事项 <span className="muted">{events.length} 项</span></h3><label>事项类型 <select value={eventType || ''} onChange={e=>onEventType(e.target.value)}><option value="">全部</option>{Object.entries(eventTypeLabels).map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label></div>{eventId && !events.some(e=>e.id===eventId) && <p className="event-caution">此链接的事项不在当前地区或事项类型范围内。调整这些条件即可查看；未自动扩大范围。</p>}{events.length ? events.map(event=><EventCard key={event.id} event={event} data={data} expanded={eventId===event.id} onEvent={onEvent} />):<div className="company-empty"><p>当前范围暂无已收录的重要事项，不代表没有新动作。可调整上方地区或事项类型；其他公司入口仍保留。</p><button className="text-link" onClick={()=>onEventType('')}>清除事项类型</button></div>}<details className="company-official"><summary>公司官方来源入口（{official.length}） · 不受资料类型筛选</summary>{official.map(source=><div className="official-row" key={source.id}><OutLink href={source.entryUrl} className="text-link">{source.name}</OutLink><button className="text-link" onClick={e=>onSource(source,e)}>来源说明</button>{source.additionalEntryUrls?.map((url,index)=><OutLink key={url} href={url} className="text-link">其他官方入口 {index+1}</OutLink>)}</div>)}{!official.length && <p>未收录该主体的独立公司官方入口。相关资料原文仍可在下方打开。</p>}</details><h3 className="region-group-title">相关资料 · {docs.length} 条</h3><DateControls filters={filters} onChange={onDateChange} company />{docs.length ? docs.map(report=><ReportRow key={report.id} report={report} source={sources.find(s=>s.id===report.sourceId)} query={filters.q} filters={filters} onSource={e=>onSource(sources.find(s=>s.id===report.sourceId),e)} />):<p className="company-empty">当前范围暂无匹配收录，可调整资料筛选。</p>}</section>;
}
